module.exports = Object.freeze({
    NEW_REQUEST: "NEW_REQUEST",
    SERVICE_ACCEPTED: "SERVICE_ACCEPTED",
    SERVICE_WAITING: "SERVICE_WAITING",
    SERVICE_STARTED: "SERVICE_STARTED",
    COMPLETED_REQUEST: "COMPLETED_REQUEST",
    SERVICE_COMPLETE: "SERVICE_COMPLETE",
    SERVICE_COMPLETE_REJECT: "SERVICE_COMPLETE_REJECT",
    REVIEW: "REVIEW",
    DISPUTE_CREATE: "DISPUTE_CREATE",
    DISPUTE_RESOLVED: "DISPUTE_RESOLVED",
    REFUND_INIT: "REFUND_INIT",
    MESSAGE: "MESSAGE",
    ACCOUNT_VERIFICATION: "ACCOUNT_VERIFICATION",
    ACCOUNT_BLOCKED: "ACCOUNT_BLOCKED",
    SERVICE_PAUSED: "SERVICE_PAUSED",
    SERVICE_RESUMED: "SERVICE_RESUMED"
});