name: 🚀 stage deployment
on:
  push:
    branches: [stage]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST_STAGE}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY_STAGE}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME_STAGE}} # User of the server you want to ssh into
     
          script: |
            cd propwalt-node-js 
            git pull origin stage
            npm install
            pm2 restart 0
            echo 'Deployment successful to ec2 ocean' 
